#
###################################
# Site wide configuration
####################################
#
title: CodeExplore
email: Saman.Sattari@gmail.com
description:
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url:"http://samansattari.github.io/codeexplore"

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Saman Sattari
  avatar: saman.jpeg
  job: "Software Engineer"
  bio:
  email:
  disqus-shortname:
  twitter: SamNSatt
  google:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: SamanSattari
  stackoverflow: 1116502/saman #   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: saman-sattari-khavas-5bb13a18
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
